### PR TITLE
SDK Update

### PR DESCRIPTION
**Pull request by ZimM-LostPolygon**
- Prioritize write client for getting nonce
- Implemented speculative nonce
- Fixed concurrency issues in `CryptoUtils`
- Increment retry delay on invalid nonce exponentially instead
- Fixed tests to compile with Solidity 0.5.0 compiler

### CODE REVIEW

**Comment by ZimM-LostPolygon** [comment]
@enlight Not sure I get it - if the nonces *do* match, what should the client do then?

**Comment by enlight** [comment]
Could either increment the last sent nonce, or wait a bit and query for another nonce. The latter is the safer option because if the node is under load all those txs with the speculative nonces may just end up flooding the tx cache, and then eventually failing the nonce check when the node finally runs them.

**Comment by ZimM-LostPolygon** [comment]
@enlight The client only "works" with one transaction at a time, never waiting for multiple transaction at the same moment, so I don't think that can really happen. That said, retrying with the same nonce that's known to fail does indeed make little sense, waiting a bit and retrying until we get a new nonce is better.

**Comment by ZimM-LostPolygon** [comment]
@enlight Perhaps you can merge it as it is now? I'm not sure when I'll get around to improving that bit, but it'd be helpful for other people in master anyway.

**Pull request merged**
